// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package counter

import (
	"errors"
	"fmt"
	"strconv"
	"math/big"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/allowlist"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 1 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	// This contract also uses AllowList precompile.
	// You should also increase gas costs of functions that read from AllowList storage.
	GetCounterGasCost      uint64 = contract.ReadGasCostPerSlot
	IncreaseCounterGasCost uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
)

// Singleton StatefulPrecompiledContract and signatures.
var (
	ErrCannotIncreaseCounter = errors.New("non-enabled cannot call increaseCounter")
	ErrInputExceedsLimit = errors.New("input value is longer than 32 bytes")

	// CounterRawABI contains the raw ABI of Counter contract.
	//go:embed contract.abi
	CounterRawABI string

	CounterABI = contract.ParseABI(CounterRawABI)

	CounterPrecompile = createCounterPrecompile()

	storageKeyHash = common.BytesToHash([]byte("storageKey"))
)

// GetCounterAllowListStatus returns the role of [address] for the Counter list.
func GetCounterAllowListStatus(stateDB contract.StateDB, address common.Address) allowlist.Role {
	return allowlist.GetAllowListStatus(stateDB, ContractAddress, address)
}

// SetCounterAllowListStatus sets the permissions of [address] to [role] for the
// Counter list. Assumes [role] has already been verified as valid.
// This stores the [role] in the contract storage with address [ContractAddress]
// and [address] hash. It means that any reusage of the [address] key for different value
// conflicts with the same slot [role] is stored.
// Precompile implementations must use a different key than [address] for their storage.
func SetCounterAllowListStatus(stateDB contract.StateDB, address common.Address, role allowlist.Role) {
	allowlist.SetAllowListRole(stateDB, ContractAddress, address, role)
}

// PackGetCounter packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetCounter() ([]byte, error) {
	return CounterABI.Pack("getCounter")
}

// PackGetCounterOutput attempts to pack given result of type string
// to conform the ABI outputs.
func PackGetCounterOutput(result string) ([]byte, error) {
	return CounterABI.PackOutput("getCounter", result)
}

func GetStorage(stateDB contract.StateDB) string {
    value := stateDB.GetState(ContractAddress, storageKeyHash)
    return string(common.TrimLeftZeroes(value.Bytes()))
}

func getCounter(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetCounterGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE

    // Get the current state
    currentState := accessibleState.GetStateDB()
    // Get the value set at recipient
    value := GetStorage(currentState)
    packedOutput, err := PackGetCounterOutput(value)
    if err != nil {
        return nil, remainingGas, err
    }

    // Return the packed output and the remaining gas
    return packedOutput, remainingGas, nil

}

// UnpackIncreaseCounterInput attempts to unpack [input] into the string type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackIncreaseCounterInput(input []byte) (string, error) {
	res, err := CounterABI.UnpackInput("increaseCounter", input)
	if err != nil {
		return "", err
	}
	unpacked := *abi.ConvertType(res[0], new(string)).(*string)
	return unpacked, nil
}

// PackIncreaseCounter packs [response] of type string into the appropriate arguments for increaseCounter.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackIncreaseCounter(response string) ([]byte, error) {
	return CounterABI.Pack("increaseCounter", response)
}

func StoreInput(stateDB contract.StateDB, input string) {
    inputPadded := common.LeftPadBytes([]byte(input), common.HashLength)
    inputHash := common.BytesToHash(inputPadded)

    stateDB.SetState(ContractAddress, storageKeyHash, inputHash)
}

func increaseCounter(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, IncreaseCounterGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the IncreaseCounterInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackIncreaseCounterInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and IncreaseCounter is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotIncreaseCounter, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	if len(inputStruct) > common.HashLength {
        return nil, 0, ErrInputExceedsLimit
    }

	s1 := GetStorage(stateDB)

	if inputStruct == "" {
		inputStruct = "1"
	}

	n1, err := strconv.Atoi(s1)
	n2, err := strconv.Atoi(inputStruct)

	result := strconv.Itoa(n1 + n2)
    StoreInput(stateDB, result)

	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createCounterPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.
// Access to the getters/setters is controlled by an allow list for ContractAddress.
func createCounterPrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction
	functions = append(functions, allowlist.CreateAllowListFunctions(ContractAddress)...)

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"getCounter":      getCounter,
		"increaseCounter": increaseCounter,
	}

	for name, function := range abiFunctionMap {
		method, ok := CounterABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
